name: Todo list CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install backend dependencies
        run: |
          cd backend
          yarn install

      - name: Run backend tests
        run: |
          cd backend
          yarn run test

  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install

      - name: Run frontend tests
        run: |
          cd frontend
          yarn run test

      - name: Run frontend e2e tests
        run: |
          npx playwright test --project=chromium
